<H1>PANDAS</H1>

<h4>pandas objects can be thought of as enhanced versions of numpy structured arrays in which rows and columns are identified with rather than simple integer indices.</h4>

In [2]:
import numpy as np 
import pandas as pd

Pandas Series Object

In [3]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values, data.index, data[1], data[1:3]

(array([0.25, 0.5 , 0.75, 1.  ]),
 RangeIndex(start=0, stop=4, step=1),
 np.float64(0.5),
 1    0.50
 2    0.75
 dtype: float64)

In [65]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','d'])
data, data['b']

(a    0.25
 b    0.50
 c    0.75
 d    1.00
 dtype: float64,
 np.float64(0.5))

In [66]:
data[(data > 0.3) & (data < 0.8)] #masking/

b    0.50
c    0.75
dtype: float64

In [69]:
# fancy indexing
data[['a', 'd']]

a    0.25
d    1.00
dtype: float64

In [70]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: str

In [72]:
data[1], data[1:3], data.loc[1], data.iloc[1:3]

('a',
 3    b
 5    c
 dtype: str,
 'a',
 3    b
 5    c
 dtype: str)

In [15]:
f1_drivers_dict = {
    'max verstappen' : 4,
    'lewis hamilton' : 7,
    'charles leclerc' : 0
}
f1_drivers = pd.Series(f1_drivers_dict)
f1_drivers_dict, f1_drivers, f1_drivers['max verstappen'], f1_drivers["max verstappen":"charles leclerc"]

({'max verstappen': 4, 'lewis hamilton': 7, 'charles leclerc': 0},
 max verstappen     4
 lewis hamilton     7
 charles leclerc    0
 dtype: int64,
 np.int64(4),
 max verstappen     4
 lewis hamilton     7
 charles leclerc    0
 dtype: int64)

In [16]:
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [17]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

In [18]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3,2])

3    c
2    a
dtype: str

DataFrame Object

<h4>If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names. </h4>

In [20]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [22]:
area_dict = {'California': 423967, 
             'Texas': 695662, 
             'New York': 141297,
             'Florida': 170312, 
             'Illinois|s': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois|s    149995
dtype: int64

In [25]:
states = pd.DataFrame({'population': population, 'area':area})
states

            population      area
California  38332521.0  423967.0
Florida     19552860.0  170312.0
Illinois    12882135.0       NaN
Illinois|s         NaN  149995.0
New York    19651127.0  141297.0
Texas       26448193.0  695662.0

In [26]:
states.index, states.columns

(Index(['California', 'Florida', 'Illinois', 'Illinois|s', 'New York', 'Texas'], dtype='str'),
 Index(['population', 'area'], dtype='str'))

In [27]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [56]:
'New York' in population

True

In [57]:
population.keys()

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')

In [59]:
list(population.items())

[('California', 38332521),
 ('Texas', 26448193),
 ('New York', 19651127),
 ('Florida', 19552860),
 ('Illinois', 12882135)]

In [29]:
data = [{'A':i, 'B':2*i} for i in range(1,4)]
pd.DataFrame(data)

   A  B
0  1  2
1  2  4
2  3  6

In [33]:
pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [42]:
pd.DataFrame(np.random.rand(3,2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c']
)

        foo       bar
a  0.974736  0.098474
b  0.021108  0.073127
c  0.112272  0.252928

In [47]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [48]:
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [75]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [77]:
data['density'] = data['pop'] / data['area']
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [79]:
data.keys, data.values

(<bound method NDFrame.keys of               area       pop     density
 California  423967  38332521   90.413926
 Texas       695662  26448193   38.018740
 New York    141297  19651127  139.076746
 Florida     170312  19552860  114.806121
 Illinois    149995  12882135   85.883763>,
 array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
        [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
        [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
        [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
        [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]]))

In [80]:
data.T

           California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [81]:
data.loc[data.density > 100, ['pop', 'density']]

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

<h3>Index Object</h3>

In [51]:
ind = pd.Index([1,2,3,4,5,6])
ind, ind[1], ind[::2]

(Index([1, 2, 3, 4, 5, 6], dtype='int64'),
 np.int64(2),
 Index([1, 3, 5], dtype='int64'))

In [52]:
ind.size, ind.shape, ind.ndim, ind.dtype

(6, (6,), 1, dtype('int64'))

TypeError("Index does not support mutable operations")

In [54]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA, indB

(Index([1, 3, 5, 7, 9], dtype='int64'), Index([2, 3, 5, 7, 11], dtype='int64'))

In [55]:
indA & indB, indA | indB, indA ^ indB

(Index([0, 3, 5, 7, 9], dtype='int64'),
 Index([3, 3, 5, 7, 11], dtype='int64'),
 Index([3, 0, 0, 0, 2], dtype='int64'))

In [85]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [86]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [87]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [88]:
np.sin(df * np.pi / 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

UFuncs: Index Alignment

In [89]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name='population')

In [90]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [93]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [96]:
A.add(B, fill_value=2)

0    4.0
1    5.0
2    9.0
3    7.0
dtype: float64

Index alignment in DataFrame

In [103]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
A

    A   B
0   9   3
1  17  11

In [104]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
B

   B  A  C
0  1  9  3
1  7  6  8
2  7  4  1

In [105]:
A+B

      A     B   C
0  18.0   4.0 NaN
1  23.0  18.0 NaN
2   NaN   NaN NaN

In [106]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

      A     B     C
0  18.0   4.0  13.0
1  23.0  18.0  18.0
2  14.0  17.0  11.0

In [107]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

dtype = object
41.6 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
2.57 ms ± 40.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [108]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [109]:
1 + np.nan, 0 *  np.nan

(nan, nan)

In [110]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

Pandas automatically converts the None to a NaN value

In [111]:
data.isnull()

             area    pop  density
California  False  False    False
Texas       False  False    False
New York    False  False    False
Florida     False  False    False
Illinois    False  False    False

In [112]:
data[data.notnull()]

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [113]:
df = pd.DataFrame([1, None, 0, -2])
df.dropna()

     0
0  1.0
2  0.0
3 -2.0

In [115]:
df.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [116]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [117]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [123]:
# forward-fill
data.fillna(value=1)

a    1.0
b    1.0
c    2.0
d    1.0
e    3.0
dtype: float64

In [124]:
index = [('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [127]:
pop = pop.reindex(index)
pop

California  2000   NaN
            2010   NaN
New York    2000   NaN
            2010   NaN
Texas       2000   NaN
            2010   NaN
dtype: float64

In [128]:
pop_df = pop.unstack()
pop_df

            2000  2010
California   NaN   NaN
New York     NaN   NaN
Texas        NaN   NaN

In [129]:
pop_df.stack()

California  2000   NaN
            2010   NaN
New York    2000   NaN
            2010   NaN
Texas       2000   NaN
            2010   NaN
dtype: float64

In [130]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

                 total  under18
California 2000    NaN  9267089
           2010    NaN  9284094
New York   2000    NaN  4687374
           2010    NaN  4318033
Texas      2000    NaN  5906301
           2010    NaN  6879014

In [134]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

        data1     data2
a 1  0.370876  0.586639
  2  0.993589  0.963314
b 1  0.042006  0.064556
  2  0.676757  0.223546

In [135]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [136]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [137]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [138]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [140]:
pop

California  2000   NaN
            2010   NaN
New York    2000   NaN
            2010   NaN
Texas       2000   NaN
            2010   NaN
dtype: float64

In [141]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000   NaN
            2010   NaN
New York    2000   NaN
            2010   NaN
Texas       2000   NaN
            2010   NaN
dtype: float64

In [142]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      23.0  37.3  42.0  36.6  44.0  35.2
     2      24.0  37.1  29.0  37.0  29.0  36.7
2014 1      36.0  36.0  43.0  37.8  39.0  36.4
     2      28.0  35.4  25.0  37.2  28.0  35.7

In [143]:
health_data['Guido']

type          HR  Temp
year visit
2013 1      42.0  36.6
     2      29.0  37.0
2014 1      43.0  37.8
     2      25.0  37.2

In [144]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: str

In [147]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [148]:
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [151]:
df3 = pd.merge(df1,df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [154]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [155]:
ser.sum(), ser.mean()

(np.float64(2.811925491708157), np.float64(0.5623850983416314))

In [156]:
df = pd.DataFrame({'A': rng.rand(5), 'B': rng.rand(5)})
df

          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [157]:
df.mean(), df.mean(axis='columns')

(A    0.477888
 B    0.443420
 dtype: float64,
 0    0.088290
 1    0.513997
 2    0.849309
 3    0.406727
 4    0.444949
 dtype: float64)

Aggregation	Description

count()	Total number of items

first(), last()	First and last item

mean(), median()	Mean and median

min(), max()	Minimum and maximum

std(), var()	Standard deviation and variance

mad()	Mean absolute deviation

prod()	Product of all items

sum()	Sum of all items

In [160]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(6)}, columns=['key', 'data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [161]:
df.groupby('key')

In [162]:
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [163]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1': range(6),
                   'data2': rng.randint(0, 10, 6)},
                   columns = ['key', 'data1', 'data2'])
df

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [164]:
df.groupby('key').aggregate(['min', np.median, max])

    data1            data2
      min median max   min median max
key
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [165]:
df.groupby('key').aggregate({'data1': 'min', 'data2': 'max'})

     data1  data2
key
A        0      5
B        1      7
C        2      9

In [166]:
df.groupby('key').transform(lambda x: x - x.mean())

   data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

Vectorized String Operations

In [168]:
data = ['peter', 'Paul', 'MARY', 'gUIDO']
[s.capitalize() for s in data]

['Peter', 'Paul', 'Mary', 'Guido']

In [169]:
names = pd.Series(data)
names

0    peter
1     Paul
2     MARY
3    gUIDO
dtype: str

In [170]:
names.str.capitalize()

0    Peter
1     Paul
2     Mary
3    Guido
dtype: str

In [172]:
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam', 'Eric Idle', 'Terry Jones', 'Michael Palin'])
monte

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: str


len()	lower()	translate()	islower()

ljust()	upper()	startswith()	isupper()

rjust()	find()	endswith()	isnumeric()

center()	rfind()	isalnum()	isdecimal()

zfill()	index()	isalpha()	split()

strip()	rindex()	isdigit()	rsplit()

rstrip()	capitalize()	isspace()	partition()

lstrip()	swapcase()	istitle()	rpartition()

In [173]:
monte.str.startswith('T')

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [174]:
monte.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object


Method	Description

match()	Call re.match() on each element, returning a boolean.

extract()	Call re.match() on each element, returning matched groups as strings.

findall()	Call re.findall() on each element

replace()	Replace occurrences of pattern with some other string

contains()	Call re.search() on each element, returning a boolean

count()	Count occurrences of pattern

split()	Equivalent to str.split(), but accepts regexps

rsplit()	Equivalent to str.rsplit(), but accepts regexps

In [175]:
monte.str.extract('([A-Za-z]+)', expand=False)

0     Graham
1       John
2      Terry
3       Eric
4      Terry
5    Michael
dtype: str

In [176]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

In [177]:
monte.str[0:3]

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: str

In [178]:
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

In [181]:
from datetime import datetime
datetime(year=2006, month=5, day=1)

datetime.datetime(2006, 5, 1, 0, 0)

In [184]:
from dateutil import parser
date = parser.parse("1st of July, 2015")
date

datetime.datetime(2015, 7, 1, 0, 0)

In [185]:
date.strftime('%A')

'Wednesday'

In [187]:
date = np.array('2015-07-04', dtype=np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [188]:
date + np.arange(12)

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

In [189]:
np.datetime64('2015-07-04 12:59:59.50', 'ns')

np.datetime64('2015-07-04T12:59:59.500000000')

In [190]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04', '2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index=index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [193]:
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015', '2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[us]', freq=None)

In [194]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[us]', freq='D')

In [195]:
pd.date_range('2015-07-03', periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[us]', freq='D')

In [198]:
nrows, ncols = 100000, 100
rng = np.random.RandomState(42)
df1, df2, df3, df4 = (pd.DataFrame(rng.rand(nrows, ncols)) for i in range(4))
df1, df2, df3, df4

(             0         1         2         3         4         5         6   \
 0      0.374540  0.950714  0.731994  0.598658  0.156019  0.155995  0.058084
 1      0.031429  0.636410  0.314356  0.508571  0.907566  0.249292  0.410383
 2      0.642032  0.084140  0.161629  0.898554  0.606429  0.009197  0.101472
 3      0.051682  0.531355  0.540635  0.637430  0.726091  0.975852  0.516300
 4      0.103124  0.902553  0.505252  0.826457  0.320050  0.895523  0.389202
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.071979  0.439323  0.188588  0.586705  0.640611  0.662409  0.318503
 99996  0.313411  0.010490  0.469216  0.600825  0.451085  0.496918  0.983128
 99997  0.560873  0.647396  0.043068  0.282439  0.042950  0.346690  0.954034
 99998  0.710115  0.067999  0.611329  0.136199  0.054724  0.018160  0.911428
 99999  0.116834  0.461155  0.754556  0.250272  0.864631  0.588966  0.358260

              7         8         9   ...        90        91        92  \
 0      0.866176  0.601115  0.708073  ...  0.119594  0.713245  0.760785
 1      0.755551  0.228798  0.076980  ...  0.093103  0.897216  0.900418
 2      0.663502  0.005062  0.160808  ...  0.030500  0.037348  0.822601
 3      0.322956  0.795186  0.270832  ...  0.990505  0.412618  0.372018
 4      0.010838  0.905382  0.091287  ...  0.455657  0.620133  0.277381
 ...         ...       ...       ...  ...       ...       ...       ...
 99995  0.600419  0.609742  0.390592  ...  0.122887  0.491140  0.032855
 99996  0.422056  0.719077  0.045588  ...  0.072444  0.715574  0.300257
 99997  0.603182  0.447768  0.888498  ...  0.880079  0.508377  0.442052
 99998  0.762005  0.245312  0.891027  ...  0.249632  0.894231  0.342761
 99999  0.655541  0.946702  0.145819  ...  0.298095  0.496018  0.990856

              93        94        95        96        97        98        99
 0      0.561277  0.770967  0.493796  0.522733  0.427541  0.025419  0.107891
 1      0.633101  0.339030  0.349210  0.725956  0.897110  0.887086  0.779876
 2      0.360191  0.127061  0.522243  0.769994  0.215821  0.622890  0.085347
 3      0.776413  0.340804  0.930757  0.858413  0.428994  0.750871  0.754543
 4      0.188121  0.463698  0.353352  0.583656  0.077735  0.974395  0.986211
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.567250  0.428673  0.421092  0.021024  0.398596  0.405897  0.869783
 99996  0.087290  0.130703  0.549202  0.287877  0.589258  0.516884  0.254370
 99997  0.621332  0.314942  0.131085  0.697310  0.111705  0.397560  0.988347
 99998  0.844330  0.659797  0.835561  0.117920  0.211202  0.931760  0.296913
 99999  0.368719  0.837910  0.244971  0.061637  0.933295  0.245149  0.388890

 [100000 rows x 100 columns],
              0         1         2         3         4         5         6   \
 0      0.926538  0.382461  0.871469  0.761471  0.328826  0.988821  0.120738
 1      0.715167  0.490948  0.904532  0.319521  0.582585  0.980330  0.019068
 2      0.975796  0.049902  0.092684  0.158453  0.858309  0.652550  0.681106
 3      0.369458  0.911366  0.892686  0.763454  0.581681  0.207756  0.024249
 4      0.794953  0.714644  0.652743  0.639999  0.801813  0.223324  0.468607
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.973490  0.631437  0.720622  0.141930  0.355449  0.638325  0.599268
 99996  0.704523  0.936341  0.711619  0.495312  0.029808  0.207772  0.673689
 99997  0.649755  0.352855  0.114277  0.826643  0.763885  0.168768  0.404275
 99998  0.975367  0.295327  0.642940  0.521112  0.592903  0.216556  0.203385
 99999  0.717863  0.281573  0.188958  0.903531  0.730933  0.826813  0.491981

              7         8         9   ...        90        91        92  \
 0      0.358905  0.954462  0.004711  ...  0.310465  0.816988  0.930747
 1      0.089363  0.281105  0.143648  ...  0.433028  0.132540  0.263659
 2      0.360168  0.843117  0.619341  ...  0.156821  0.772316  0.412088
 3      0.925860  0.191849  0.047043  ...  0.313598  0.566552  0.844425
 4      0.409739  0.846211  0.488558  ...  0.349061  0.986111  0.389271
 ...         ...       ...       ...  ...       ...       ...       ...
 99995  0.267570  0.715158  0.909540  ...  0.720632  0.069631  0.567910
 99996  0.776497  0.871136  0.088103  ...  0.636035  0.532702  0.744088
 99997  0.079896  0.169630  0.953930  ...  0.352673  0.635799  0.674737
 99998  0.618827  0.191058  0.853803  ...  0.229260  0.459856  0.601687
 99999  0.364553  0.069016  0.354719  ...  0.443628  0.101887  0.265541

              93        94        95        96        97        98        99
 0      0.111477  0.772517  0.801181  0.466825  0.005912  0.705110  0.487674
 1      0.339079  0.234842  0.507921  0.544545  0.197424  0.432392  0.218104
 2      0.796167  0.548580  0.722526  0.141587  0.459266  0.128221  0.661666
 3      0.079068  0.338430  0.921877  0.856621  0.285027  0.505441  0.571166
 4      0.428010  0.645183  0.998789  0.805533  0.310009  0.876316  0.946936
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.373837  0.513205  0.318192  0.354705  0.785753  0.625627  0.893857
 99996  0.741955  0.967174  0.998244  0.632177  0.080062  0.289840  0.382859
 99997  0.290065  0.463327  0.358685  0.952076  0.979473  0.186088  0.000481
 99998  0.851845  0.740290  0.732748  0.416686  0.585025  0.785590  0.161383
 99999  0.134110  0.664314  0.536308  0.656200  0.041181  0.339916  0.646908

 [100000 rows x 100 columns],
              0         1         2         3         4         5         6   \
 0      0.381785  0.884280  0.450580  0.889203  0.400178  0.329899  0.374920
 1      0.575967  0.057404  0.320802  0.174745  0.708598  0.165073  0.852300
 2      0.553476  0.657017  0.721860  0.058866  0.818086  0.882324  0.633707
 3      0.841810  0.738977  0.768721  0.352721  0.454399  0.915650  0.164899
 4      0.069417  0.370450  0.329881  0.882140  0.688254  0.393034  0.288496
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.653439  0.577346  0.825217  0.780580  0.917081  0.212901  0.593976
 99996  0.563796  0.434376  0.829309  0.620991  0.626362  0.379460  0.444091
 99997  0.422315  0.444597  0.810355  0.398208  0.847200  0.754816  0.404969
 99998  0.336348  0.520296  0.724958  0.376817  0.398625  0.809996  0.634984
 99999  0.520489  0.929742  0.701161  0.079113  0.477068  0.568126  0.693307

              7         8         9   ...        90        91        92  \
 0      0.289165  0.856012  0.170531  ...  0.232548  0.427080  0.687908
 1      0.841379  0.810541  0.867123  ...  0.205949  0.183090  0.481792
 2      0.786487  0.107093  0.659608  ...  0.725832  0.627375  0.387747
 3      0.872948  0.419942  0.671492  ...  0.917378  0.928159  0.034869
 4      0.248113  0.835122  0.668993  ...  0.723569  0.378604  0.294903
 ...         ...       ...       ...  ...       ...       ...       ...
 99995  0.254550  0.842179  0.516361  ...  0.364815  0.103298  0.065614
 99996  0.538880  0.217070  0.774119  ...  0.791762  0.015829  0.226943
 99997  0.438984  0.671320  0.907817  ...  0.337849  0.622438  0.265944
 99998  0.759740  0.779359  0.371569  ...  0.431090  0.524956  0.822374
 99999  0.260624  0.128251  0.217928  ...  0.782768  0.653314  0.680052

              93        94        95        96        97        98        99
 0      0.990223  0.532107  0.291570  0.604532  0.510344  0.178462  0.816248
 1      0.479930  0.360370  0.920427  0.515166  0.698365  0.925812  0.272917
 2      0.204460  0.973627  0.262530  0.912395  0.852041  0.050451  0.668992
 3      0.679377  0.351755  0.233520  0.620001  0.338868  0.797963  0.447284
 4      0.595871  0.940018  0.544825  0.030322  0.157838  0.364742  0.932007
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.843703  0.140892  0.981793  0.316524  0.505177  0.011505  0.435139
 99996  0.322211  0.151096  0.575034  0.594906  0.147203  0.341684  0.998307
 99997  0.828262  0.727854  0.753011  0.260171  0.341418  0.820072  0.341222
 99998  0.922118  0.004101  0.340958  0.561711  0.405932  0.219157  0.935296
 99999  0.468902  0.661500  0.156686  0.640828  0.288135  0.313195  0.151012

 [100000 rows x 100 columns],
              0         1         2         3         4         5         6   \
 0      0.773222  0.022870  0.135256  0.547153  0.112734  0.382484  0.282446
 1      0.608169  0.141071  0.560629  0.028672  0.017801  0.928250  0.939959
 2      0.790280  0.450114  0.316514  0.443655  0.961636  0.183530  0.092308
 3      0.062328  0.129402  0.951153  0.674908  0.706534  0.069130  0.331226
 4      0.139670  0.010372  0.683865  0.662876  0.593358  0.273290  0.001748
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.249413  0.103119  0.542195  0.694760  0.839056  0.298043  0.033077
 99996  0.667714  0.867746  0.830593  0.561841  0.444891  0.529657  0.436121
 99997  0.309121  0.907930  0.136517  0.269726  0.505400  0.444741  0.661107
 99998  0.659346  0.075041  0.887846  0.093171  0.231719  0.223407  0.006966
 99999  0.945243  0.829126  0.741130  0.286036  0.619342  0.596187  0.504068

              7         8         9   ...        90        91        92  \
 0      0.479390  0.973054  0.968159  ...  0.742549  0.014689  0.638707
 1      0.865063  0.125569  0.062302  ...  0.563912  0.085168  0.545653
 2      0.563372  0.137717  0.493172  ...  0.943914  0.999072  0.656912
 3      0.421508  0.578126  0.674810  ...  0.026716  0.690321  0.373365
 4      0.173523  0.578557  0.084194  ...  0.472835  0.914288  0.634008
 ...         ...       ...       ...  ...       ...       ...       ...
 99995  0.225335  0.239353  0.229226  ...  0.947957  0.805594  0.573097
 99996  0.835338  0.047874  0.663011  ...  0.027973  0.220472  0.388495
 99997  0.891012  0.348976  0.738745  ...  0.588556  0.329875  0.104201
 99998  0.109956  0.111096  0.362624  ...  0.698372  0.161685  0.457085
 99999  0.103360  0.735239  0.624025  ...  0.283123  0.159090  0.459874

              93        94        95        96        97        98        99
 0      0.557382  0.935098  0.161364  0.792444  0.789514  0.522443  0.575358
 1      0.062591  0.079648  0.904816  0.570289  0.112442  0.187270  0.167751
 2      0.879790  0.801385  0.020247  0.274610  0.013139  0.884154  0.128746
 3      0.361318  0.044817  0.219551  0.684745  0.104272  0.996603  0.256260
 4      0.922544  0.063849  0.203463  0.805392  0.097480  0.733605  0.278122
 ...         ...       ...       ...       ...       ...       ...       ...
 99995  0.301067  0.463632  0.949715  0.108855  0.235437  0.266807  0.399797
 99996  0.647074  0.671423  0.921422  0.450065  0.909240  0.317553  0.169943
 99997  0.929684  0.563298  0.089244  0.281686  0.746781  0.412429  0.352413
 99998  0.654283  0.528957  0.669479  0.036532  0.716870  0.264882  0.557014
 99999  0.486491  0.944669  0.672019  0.101245  0.799393  0.795580  0.571488

 [100000 rows x 100 columns])

In [199]:
%timeit df1 + df2 + df3 + df4

86.1 ms ± 4.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [200]:
%timeit pd.eval('df1 + df2 + df3 + df4')

89.4 ms ± 4.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [201]:
df1, df2, df3, df4, df5 = (pd.DataFrame(rng.randint(0, 1000, (100, 3))) for i in range(5))

In [202]:
df.values.nbytes

144

In [205]:
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [206]:
df_13 = pd.DataFrame({'foo' : [7, -5, 7, 4, 2, 0, 4, 7],
                   'bar' : [-5, 4, 2, 0, 4, 7, 7, 8],
                   'baz' : [-1, 2, 3, 0, 5, 9, 9, 5]})
df_13

   foo  bar  baz
0    7   -5   -1
1   -5    4    2
2    7    2    3
3    4    0    0
4    2    4    5
5    0    7    9
6    4    7    9
7    7    8    5

In [207]:
df_13.rank()

   foo  bar  baz
0  7.0  1.0  1.0
1  1.0  4.5  3.0
2  7.0  3.0  4.0
3  4.5  2.0  2.0
4  3.0  4.5  5.5
5  2.0  6.5  7.5
6  4.5  6.5  7.5
7  7.0  8.0  5.5

In [208]:
df_13.rank(axis=1)

   foo  bar  baz
0  3.0  1.0  2.0
1  1.0  3.0  2.0
2  3.0  1.0  2.0
3  3.0  1.5  1.5
4  1.0  2.0  3.0
5  1.0  2.0  3.0
6  1.0  2.0  3.0
7  2.0  3.0  1.0

<h2>scikit learn</h2>

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris.data.shape, iris.keys, iris.target.shape, iris.target_names, iris.feature_names

((150, 4),
 <function Bunch.keys>,
 (150,),
 array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

K-Nearest Neighbors Classifier

In [17]:
import numpy as np
import sklearn

print(np.__version__)
print(sklearn.__version__)

2.4.6
1.9.0

In [15]:
from sklearn import neighbors, datasets

iris = datasets.load_iris()
X, y = iris.data, iris.target

# create the model
knn = neighbors.KNeighborsClassifier(n_neighbors=5, weights='uniform')

# fit the model
knn.fit(X, y)

# What kind of iris has 3cm x 5cm sepal and 4cm x 2cm petal?
X_pred = [3, 5, 4, 2]
result = knn.predict([X_pred, ])

print(iris.target_names[result])
print(iris.target_names)
print(knn.predict_proba([X_pred, ]))

TypeError: numpy._core._multiarray_umath._unique_hash() takes no keyword arguments